export const creationarr = [
  {
    name: '암흑 수류탄',
    itemCode: 101151,
    createBundle: 3,
    energy: 144,
    createTime: 1800,
    createCost: 15,
    category: '배틀아이템',
    ingredient: [
      { name: '목재', ingredientCount: 17 },
      { name: '부드러운 목재', ingredientCount: 12 },
      { name: '튼튼한 목재', ingredientCount: 4 },
    ],
  },
  {
    name: '빛나는 암흑 수류탄',
    itemCode: 101924,
    createBundle: 2,
    energy: 216,
    createTime: 2700,
    createCost: 15,
    category: '배틀아이템',
    ingredient: [
      { name: '암흑 수류탄', ingredientCount: 3 },
      { name: '튼튼한 목재', ingredientCount: 4 },
    ],
  },
  {
    name: '아비도스 융화 재료(고고학)',
    itemCode: 6861012,
    createBundle: 10,
    energy: 288,
    createTime: 3600,
    createCost: 400,
    category: '특수',
    ingredient: [
      { name: '아비도스 유물', ingredientCount: 33 },
      { name: '희귀한 유물', ingredientCount: 45 },
      { name: '고대 유물', ingredientCount: 86 },
    ],
  },
  {
    name: '아비도스 융화 재료(낚시)',
    itemCode: 6861012,
    createBundle: 10,
    energy: 288,
    createTime: 3600,
    createCost: 400,
    category: '특수',
    ingredient: [
      { name: '아비도스 태양 잉어', ingredientCount: 33 },
      { name: '붉은 살 생선', ingredientCount: 45 },
      { name: '생선', ingredientCount: 86 },
    ],
  },
  {
    name: '[일품] 거장의 채끝 스테이크 정식',
    itemCode: 6854020,
    createBundle: 10,
    energy: 288,
    createTime: 3600,
    createCost: 80,
    category: '요리',
    ingredient: [
      { name: '아비도스 태양 잉어', ingredientCount: 75 },
      { name: '아비도스 두툼한 생고기', ingredientCount: 65 },
      { name: '붉은 살 생선', ingredientCount: 97 },
      { name: '다듬은 생고기', ingredientCount: 84 },
      { name: '생선', ingredientCount: 129 },
      { name: '두툼한 생고기', ingredientCount: 112 },
    ],
  },
  {
    name: '달인용 낚시 도구',
    itemCode: 6811605,
    createBundle: 1,
    energy: 2592,
    createTime: 32400,
    createCost: 500,
    category: '생활도구',
    ingredient: [
      { name: '달인용 제작 키트', ingredientCount: 1 },
      { name: '희귀한 유물', ingredientCount: 92 },
      { name: '도구 제작 부품', ingredientCount: 82 },
      { name: '철광석', ingredientCount: 122 },
    ],
  },
];
